name: tezda_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  get_it:
  retrofit: ^4.0.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  go_router: 11.1.4
  flutter_svg: ^2.0.7
  shared_preferences:
  flutter_secure_storage:
  google_fonts: 6.1.0
  flutter_riverpod: ^2.3.6
  fluttertoast: ^8.2.2
  pretty_dio_logger: ^1.2.0-beta-1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.17.0
  lottie: ^3.0.0
  favorite_button: ^0.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  flutter_gen_runner:
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter_gen:
  output: lib/common/gen/
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/png/
    - assets/svg/
    - assets/animations/
